steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/imposing-avatar-451119-s0/shavez-100938606/app:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/imposing-avatar-451119-s0/shavez-100938606/app:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'gcp-cicd-app2',
         '--image', 'us-central1-docker.pkg.dev/imposing-avatar-451119-s0/shavez-100938606/app:$COMMIT_SHA',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']

options:
  logging: 'CLOUD_LOGGING_ONLY'
